version: "3"
services:
    postgres:
        container_name: postgres-laravel-presensi
        image: "postgres:10.11"
        volumes:
            - "postgres-laravel-ac:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
volumes:
    postgres-laravel-ac: null
